[package]
name = "lnk-profile-dev"
version = "0.1.0"
authors = [ "Fintan Halpenny <fintan.halpenny@gmail.com>" ]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1"
structopt = "0.3"

[dependencies.lnk-exe]
path = "../../lnk-exe"

[dependencies.lnk-profile]
path = "../../lnk-profile"
